info_reservation:
    path:      /info_reservation
    defaults:
        _controller: FormBundle:Form:reservation

info_billet:
    path:      /info_billet
    defaults:
        _controller: FormBundle:Form:billet

info_recapitulatif:
    path:      /recapitulatif
    defaults:
        _controller: FormBundle:Form:recapitulatif

check_nombre_billets_restant:
    path:      /checkNbreBillet
    defaults:
        _controller: FormBundle:Ajax:nbreBilletsRestant

supprime_billet:
    path:      /supprime_billet
    defaults:
        _controller: FormBundle:Ajax:supprimeBillet

id_billet:
    path:      /id_billet
    defaults:
        _controller: FormBundle:Ajax:idBillet

verification_paiement:
    path:      /verification_paiement
    defaults:
        _controller: FormBundle:Ajax:verificationPaiement

validation_paiement:
    path:      /validation_paiement
    defaults:
        _controller: FormBundle:Form:validationPaiement

clear_session:
    path:      /clear
    defaults:
        _controller: FormBundle:Form:clearSession

routine:
    path:      /routine
    defaults:
        _controller: FormBundle:Form:routine

