services:
#    form.example:
#        class: FormBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

     form.calculPrix:
         class: FormBundle\CalculPrix\CalculPrix

     form.paiement:
         class: FormBundle\Paiement\Paiement

     form.email:
         class: FormBundle\Email\Email
         arguments: 
          - "@mailer"

     form.codeReservation:
         class: FormBundle\CodeReservation\CodeReservation
         



